language: cpp
compiler: gcc
before_install: 
- if [ $TRAVIS_OS_NAME == linux ]; then 
       sudo apt-add-repository -y george-edison55-precise-backports
    && sudo apt-get update 
    && sudo apt-get install libssl-dev libboost-all-dev cmake
    ; 
  fi
- if [ $TRAVIS_OS_NAME == osx ]; then 
       brew update 
    && brew unlink cmake
    && brew install openssl cmake
    && brew link --force openssl
    ; 
  fi
script: cd build && cmake .. && make
branches:
    only:
    - master
notification:
    email: true
os:
- linux
- osx
